target 'upgradr', :exclusive => true do
  pod "upgradr", :path => "../"

  pod 'AFNetworking', '~> 2.3'
end

target 'Tests', :exclusive => true do
  pod "upgradr", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
